=== petrbroz/forge-sample-gallery/schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://example.com/sample.schema.json",
    "title": "Sample",
    "description": "Information about a sample application.",
    "type": "object",
    "properties": {
        "title": {
            "type": "string",
            "description": "Sample app title."
        },
        "description": {
            "type": "string",
            "description": "Sample app description."
        },
        "tags": {
            "type": "array",
            "description": "List of tags relevant to the sample",
            "items": {
                "type": "string",
                "enum": ["viewer", "data management", "model derivative", "design automation", "bim360", "digital twin", "configurator", "iot", "phasing", "point cloud", "webhooks"]
            }
        },
        "screenshotUrl": {
            "type": "string",
            "description": "Screenshot URL"
        },
        "liveDemoUrl": {
            "type": "string",
            "description": "Live demo URL"
        },
        "sourceUrl": {
            "type": "string",
            "description": "Source code URL"
        }
    },
    "required": [
        "title"
    ]
}

=== petrbroz/forge-sample-gallery/samples/phasing-scheduling.json
{
    "$schema": "../schema.json",
    "title": "Phasing/Scheduling",
    "description": "Visualization of the project timeline phase-wise.",
    "tags": [],
    "screenshotUrl": "https://github.com/deepalics0044/_GIF/raw/master/_GIF/Forge%20BIM%20Phasing1.gif",
    "liveDemoUrl": "http://forge-bim-phasing.azurewebsites.net/"
}

=== petrbroz/forge-sample-gallery/samples/bim360-issue-editor.json
{
    "$schema": "../schema.json",
    "title": "BIM360 Issue Editor",
    "description": "Prototype application for bulk-editing BIM 360 issues using Autodesk Forge APIs.",
    "tags": [
        "bim360"
    ],
    "screenshotUrl": "https://github.com/petrbroz/bim360-issue-editor/raw/develop/docs/screenshot.png",
    "sourceUrl": "https://github.com/petrbroz/bim360-issue-editor",
    "liveDemoUrl": "https://bim360-issue-editor.herokuapp.com"
}

=== petrbroz/forge-sample-gallery/samples/bim360-clash-issue.json
{
    "$schema": "../schema.json",
    "title": "BIM360 Model Coordination: Clash Issue",
    "description": "This repository demonstrates the scenario: analyze clash issue and create clash issue from application.",
    "tags": [
        "bim360"
    ],
    "screenshotUrl": "https://github.com/Autodesk-Forge/forge-bim360-clashissue/raw/master/thumbnail.png",
    "sourceUrl": "https://github.com/Autodesk-Forge/forge-bim360-clashissue",
    "liveDemoUrl": "https://bim360-clash-issue.herokuapp.com"
}

=== petrbroz/forge-sample-gallery/samples/bim360-clash-export.json
{
    "$schema": "../schema.json",
    "title": "BIM360 Model Coordination: Clash Export",
    "description": "This repository demonstrates advanced viewing of clash raw data by Model Coordination API and demos exporting a PDF report on the clashes the user is interested in.",
    "tags": [
        "bim360"
    ],
    "screenshotUrl": "https://github.com/Autodesk-Forge/forge-bim360-clashpdfexport/raw/master/thumbnail.png",
    "sourceUrl": "https://github.com/Autodesk-Forge/forge-bim360-clashpdfexport",
    "liveDemoUrl": "https://bim360-clash-pdf-exporter.herokuapp.com"
}

=== petrbroz/forge-sample-gallery/samples/bim360-search.json
{
    "$schema": "../schema.json",
    "title": "BIM360 Search",
    "description": "Demonstrate how to index metadata into a Elasticsearch database (AWS Service) and search on it.",
    "tags": [
        "bim360"
    ],
    "screenshotUrl": "https://github.com/Autodesk-Forge/forge-bim360search/raw/master/thumbnail.gif",
    "sourceUrl": "https://github.com/Autodesk-Forge/forge-bim360search",
    "liveDemoUrl": "http://bim360search.autodesk.io"
}

=== petrbroz/forge-sample-gallery/samples/rim-configurator.json
{
    "$schema": "../schema.json",
    "title": "Rim Configurator",
    "description": "Web application that demonstrates the use of Inventor Design Automation and iLogic capabilities to create a configuration tool.",
    "tags": [
        "design automation",
        "configurator"
    ],
    "screenshotUrl": "https://github.com/sajith-subramanian/forge-rimconfigurator-inventor/raw/master/thumbnail.gif",
    "sourceUrl": "https://github.com/sajith-subramanian/forge-rimconfigurator-inventor",
    "liveDemoUrl": "https://forge-rimconfigurator-inventor.herokuapp.com"
}

=== petrbroz/forge-sample-gallery/samples/window-configurator.json
{
    "$schema": "../schema.json",
    "title": "Doors/Windows Configurator",
    "description": "Jeldwen's sales tool for choosing color/part options.",
    "tags": [
        "configurator"
    ],
    "screenshotUrl": "https://github.com/wallabyway/JELDWIN-configurator/raw/master/jeldwin-anim.gif",
    "sourceUrl": "https://github.com/wallabyway/JELDWIN-configurator",
    "liveDemoUrl": "https://www.jeld-wen.com/en-us/products/windows/builders-vinyl-v-2500/double-hung"
}

=== petrbroz/forge-sample-gallery/samples/forge-phasing-poc.json
{
    "$schema": "../schema.json",
    "title": "Forge Phasing Demo",
    "description": "Sample Autodesk Forge application providing a 4D/phasing preview capability.",
    "tags": [
        "viewer",
        "phasing"
    ],
    "screenshotUrl": "https://github.com/petrbroz/forge-phasing-poc/raw/master/screenshot.png",
    "liveDemoUrl": "https://forge-phasing-poc.herokuapp.com",
    "sourceUrl": "https://github.com/petrbroz/forge-phasing-poc"
}
