=== petrbroz/forge-sample-gallery/schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://example.com/sample.schema.json",
    "title": "Sample",
    "description": "Information about a sample application.",
    "type": "object",
    "properties": {
        "title": {
            "type": "string",
            "description": "Sample app title."
        },
        "description": {
            "type": "string",
            "description": "Sample app description."
        },
        "tags": {
            "type": "array",
            "description": "List of tags relevant to the sample",
            "items": {
                "type": "string",
                "enum": ["viewer", "data management", "model derivative", "design automation", "bim360", "digital twin", "configurator", "iot", "phasing", "point cloud", "webhooks"]
            }
        },
        "screenshotUrl": {
            "type": "string",
            "description": "Screenshot URL"
        },
        "liveDemoUrl": {
            "type": "string",
            "description": "Live demo URL"
        },
        "sourceUrl": {
            "type": "string",
            "description": "Source code URL"
        }
    },
    "required": [
        "title"
    ]
}

=== petrbroz/forge-sample-gallery/samples/inventor-configurator.json
{
    "$schema": "../schema.json",
    "title": "Inventor Configurator",
    "description": "Demo application showcasing Configuration with Design Automation for Inventor.",
    "tags": [
        "design automation",
        "configurator"
    ],
    "screenshotUrl": "https://github.com/Autodesk-Forge/forge-configurator-inventor/raw/master/img/thumbnail.gif",
    "sourceUrl": "https://github.com/Autodesk-Forge/forge-configurator-inventor",
    "liveDemoUrl": "http://inventor-config-demo.autodesk.io"
}

=== petrbroz/forge-sample-gallery/samples/bim360-notifier.json
{
    "$schema": "../schema.json",
    "title": "BIM360 Notifier",
    "description": "This sample application demonstrate Webhooks notifications for changes on BIM 360 Docs, BIM 360 Team (formerly A360) and Fusion 360 to SMS, Email and chat bot.",
    "tags": [
        "bim360",
        "webhooks"
    ],
    "screenshotUrl": "https://github.com/Autodesk-Forge/forge-bim360notifier/raw/master/thumbnail.png",
    "sourceUrl": "https://github.com/Autodesk-Forge/forge-bim360notifier"
}

=== petrbroz/forge-sample-gallery/samples/bim360-clash-view.json
{
    "$schema": "../schema.json",
    "title": "BIM360 Model Coordination: Clash View",
    "description": "This repository demonstrates basic viewing of clash raw data by Model Coordination API. It lists all clash instances data, and allows the user to click one instance to highlight within Forge Viewer.",
    "tags": [
        "bim360"
    ],
    "screenshotUrl": "https://github.com/Autodesk-Forge/forge-bim360-clashview/raw/master/thumbnail.png",
    "sourceUrl": "https://github.com/Autodesk-Forge/forge-bim360-clashview",
    "liveDemoUrl": "https://bim360-clash-basic-view.herokuapp.com"
}

=== petrbroz/forge-sample-gallery/samples/forge-digital-twin.json
{
    "$schema": "../schema.json",
    "title": "Forge Digital Twin",
    "description": "Autodesk Forge application demonstrating various use cases in manufacturing, specifically in context of digital twins.",
    "tags": [
        "viewer",
        "digital twin"
    ],
    "screenshotUrl": "https://github.com/petrbroz/forge-digital-twin/raw/master/thumbnail.png",
    "liveDemoUrl": "http://forge-digital-twin.autodesk.io",
    "sourceUrl": "https://github.com/petrbroz/forge-digital-twin"
}

=== petrbroz/forge-sample-gallery/samples/forge-potree-demo.json
{
    "$schema": "../schema.json",
    "title": "Forge Point Clouds",
    "description": "Sample Autodesk Forge application showing the use of Potree pointclouds in the viewer.",
    "tags": [
        "viewer",
        "point cloud"
    ],
    "screenshotUrl": "https://github.com/petrbroz/forge-potree-demo/raw/master/screenshot.png",
    "sourceUrl": "https://github.com/petrbroz/forge-potree-demo"
}

=== petrbroz/forge-sample-gallery/samples/forge-assembly-configurator.json
{
    "$schema": "../schema.json",
    "title": "Forge Assembly Configurator",
    "description": "Simple, generic assembly configurator built using the Autodesk Forge platform.",
    "tags": [
        "viewer",
        "configurator",
        "design automation"
    ],
    "screenshotUrl": "https://camo.githubusercontent.com/bb603ef47a8eed7ce91a5c5292eafa17efa0830ccbfe3f9b477a16af33ef2dd8/68747470733a2f2f696d672e796f75747562652e636f6d2f76692f4a7a33697a6846544570732f302e6a7067",
    "liveDemoUrl": "https://forge-assembly-configurator.herokuapp.com",
    "sourceUrl": "https://github.com/petrbroz/forge-assembly-configurator"
}

=== petrbroz/forge-sample-gallery/samples/forge-iot-extensions-demo.json
{
    "$schema": "../schema.json",
    "title": "Forge IoT Extensions Demo",
    "description": "Autodesk Forge sample application visualizing IoT sensor data.",
    "tags": [
        "viewer",
        "digital twin",
        "iot"
    ],
    "screenshotUrl": "https://github.com/petrbroz/forge-iot-extensions-demo/raw/master/screenshot.png",
    "liveDemoUrl": "https://forge-iot-example.herokuapp.com",
    "sourceUrl": "https://github.com/petrbroz/forge-iot-extensions-demo"
}

=== petrbroz/forge-sample-gallery/samples/forge-disconnected.json
{
    "$schema": "../schema.json",
    "title": "Forge Disconnected",
    "description": "Sample Forge application using Service Workers and Cache APIs to provide a limited offline support.",
    "tags": [
        "viewer"
    ],
    "screenshotUrl": "https://via.placeholder.com/400x200.png",
    "liveDemoUrl": "https://forge-disconnected.autodesk.io",
    "sourceUrl": "https://github.com/petrbroz/forge-disconnected"
}
